sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t yasar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yasar/docker-react npm run test


## This is only garbage